### ISSUE TITLE
Update log-update>=5 for transitive ansi-regex CVE-2021-3807

### ISSUE THREAD

**Issue by mriedem** [ali322/progress-webpack-plugin#5]
Given this dependency chain:

```
├─┬ progress-webpack-plugin@1.0.12
│ │ └─┬ log-update@2.3.0
│ │   └─┬ wrap-ansi@3.0.1
│ │     └─┬ strip-ansi@4.0.0
│ │       └── ansi-regex@3.0.0
```

ansi-regex has a vulnerability and needs to be updated to at least 5.0.1:

https://nvd.nist.gov/vuln/detail/CVE-2021-3807

https://github.com/advisories/GHSA-93q8-gq69-wqmw

log-update 5.0.0 has an updated wrap-ansi 8.0.1:

https://github.com/sindresorhus/log-update/commit/d6d51e7c38d1e1e2f96838426c03377d4053233e

wrap-ansi 8.0.1 has a newer version of strip-ansi:

https://github.com/chalk/wrap-ansi/commit/0ff29cca85c71cf18d86919e6e900ed4d3bbaca5

And strip-ansi 7.0.1 requires ansi-regex 6.0.1:

https://github.com/chalk/strip-ansi/commit/ed41f3819c88c30bf04656bd759ab21f481293c3

From `npm audit`:

```
# Run  npm install log-update@5.0.0  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │  Inefficient Regular Expression Complexity in                │
│               │ chalk/ansi-regex                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ansi-regex                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ log-update                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ log-update > wrap-ansi > strip-ansi > ansi-regex             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-93q8-gq69-wqmw            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │  Inefficient Regular Expression Complexity in                │
│               │ chalk/ansi-regex                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ansi-regex                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ log-update                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ log-update > wrap-ansi > string-width > strip-ansi >         │
│               │ ansi-regex                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-93q8-gq69-wqmw            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by mriedem** [comment]
Also note that the old eslint version used in this project has the vulnerable ansi-regex. I care less about that since I'm just getting progress-webpack-plugin as a transitive dependency.

```
$ npm list ansi-regex
progress-webpack-plugin@1.0.12 /home/osboxes/ibmq/progress-webpack-plugin
├─┬ eslint@4.19.1
│ ├─┬ babel-code-frame@6.26.0
│ │ └─┬ chalk@1.1.3
│ │   ├─┬ has-ansi@2.0.0
│ │   │ └── ansi-regex@2.1.1 
│ │   └─┬ strip-ansi@3.0.1
│ │     └── ansi-regex@2.1.1 
│ └─┬ strip-ansi@4.0.0
│   └── ansi-regex@3.0.0
```

**Comment by gagrison** [comment]
@ali322 can you please approve this

**Comment by lorand-horvath** [comment]
@ali322 Please approve the `log-update` bump to ^5.0.0.
`progress-webpack-plugin` is currently limited to the old `log-update` ^2.1.0, which includes 2 instances of vulnerable dependencies `ansi-regex@3.0.0`. Thanks!

**Comment by lorand-horvath** [comment]
@mriedem @gagrison @ali322 
The vulnerability has been fixed in `ansi-regex@3.0.1` https://github.com/chalk/ansi-regex/commits/backport/v3
Package released on npm 3 days ago https://www.npmjs.com/package/ansi-regex/v/3.0.1
Updating your dependencies or reinstalling `progress-webpack-plugin` should pull in the fixed version 3.0.1

**Comment by ali322** [comment]
since `log-update` has been updated to 3.4.0, security vulnerability should been fixed

**Comment by lorand-horvath** [comment]
> since `log-update` has been updated to 3.4.0, security vulnerability should been fixed

Thanks for the heads up!
```
progress-webpack-plugin@1.0.15
  log-update@3.4.0
    wrap-ansi@5.1.0
      strip-ansi@5.2.0
        ansi-regex@4.1.1 - which is also fine https://github.com/chalk/ansi-regex/commits/backport/v4
```
@ali322 - is @chenli13 your alias? The latest commits are made by this new user https://github.com/ali322/progress-webpack-plugin/commits/master

**Comment by ali322** [comment]
yes

**Comment by lorand-horvath** [comment]
@ali322 I have just tested the latest version 1.0.15, which includes the new `log-update` version `3.4.0`, but unfortunately it's not working properly. When the log line exceeds the current terminal window, it goes to the next line and there are artifacts/remains from previous log lines. Also, when I try to close the dev server with Ctrl+C, the confirmation line does not appear. (I think it appears below the previous logged text, I'm not sure, but it's not there and it is very confusing).

Please see a screenshot of what's happening when I start the @vue/cli dev server (webpack 5 based). There should be only a single line starting with the current completion percentage.

![image](https://user-images.githubusercontent.com/72015221/161421902-e14b50ff-1324-47c6-9a99-d439dce75532.png)

The previous `log-update` version `2.3.0` was working correctly. Could you please revert it from 3.4.0 to 2.3.0? https://github.com/sindresorhus/log-update/blob/v2.3.0/package.json

log-update 2.3.0 is secure in terms of dependencies, because it depends on ansi-regex 3.0.1 which has the vulnerability fix included for at least a week now, please see https://github.com/chalk/ansi-regex/commits/backport/v3

I've also mentioned this in a comment above https://github.com/ali322/progress-webpack-plugin/issues/5#issuecomment-1082923118

```
log-update@2.3.0
  wrap-ansi@3.0.1
    strip-ansi@4.0.0
      ansi-regex@3.0.1 - fixed ReDoS vulnerability https://github.com/chalk/ansi-regex/commits/backport/v3
```

Thanks!

**Comment by ali322** [comment]
THX for ur contribution
